// Full service registration barrel — imports all service side-effect modules.
// Usage: import 'tsvergeos/full';

import './services/vm/index.js';
import './services/network/index.js';
import './services/machine-drive/index.js';
import './services/machine-nic/index.js';
import './services/machine-device/index.js';
import './services/machine-snapshot/index.js';
import './services/network-address/index.js';
import './services/network-rule/index.js';
import './services/network-rule-alias/index.js';
import './services/network-dns-view/index.js';
import './services/network-dns-zone/index.js';
import './services/network-dns-record/index.js';
import './services/network-host/index.js';
import './services/wireguard/index.js';
import './services/wireguard-peer/index.js';
import './services/wireguard-peer-status/index.js';
import './services/ipsec/index.js';
import './services/ipsec-phase1/index.js';
import './services/ipsec-phase2/index.js';
import './services/ipsec-connection/index.js';
import './services/machine-stats/index.js';
import './services/machine-drive-stats/index.js';
import './services/machine-nic-stats/index.js';
import './services/machine-drive-phys/index.js';
import './services/volume/index.js';
import './services/volume-cifs-share/index.js';
import './services/volume-nfs-share/index.js';
import './services/volume-snapshot/index.js';
import './services/volume-sync/index.js';
