import { defineConfig } from 'tsup';

export default defineConfig({
	entry: {
		index: 'src/index.ts',
		types: 'src/types.ts',
		full: 'src/full.ts',
		'services/vm/index': 'src/services/vm/index.ts',
		'services/network/index': 'src/services/network/index.ts',
		'services/machine-drive/index': 'src/services/machine-drive/index.ts',
		'services/machine-device/index': 'src/services/machine-device/index.ts',
		'services/machine-nic/index': 'src/services/machine-nic/index.ts',
		'services/machine-snapshot/index': 'src/services/machine-snapshot/index.ts',
		'services/network-address/index': 'src/services/network-address/index.ts',
		'services/network-rule/index': 'src/services/network-rule/index.ts',
		'services/network-rule-alias/index': 'src/services/network-rule-alias/index.ts',
		'services/network-dns-view/index': 'src/services/network-dns-view/index.ts',
		'services/network-dns-zone/index': 'src/services/network-dns-zone/index.ts',
		'services/network-dns-record/index': 'src/services/network-dns-record/index.ts',
		'services/network-host/index': 'src/services/network-host/index.ts',
		'services/wireguard/index': 'src/services/wireguard/index.ts',
		'services/wireguard-peer/index': 'src/services/wireguard-peer/index.ts',
		'services/ipsec/index': 'src/services/ipsec/index.ts',
		'services/ipsec-phase1/index': 'src/services/ipsec-phase1/index.ts',
		'services/ipsec-phase2/index': 'src/services/ipsec-phase2/index.ts',
		'services/ipsec-connection/index': 'src/services/ipsec-connection/index.ts',
		'services/machine-stats/index': 'src/services/machine-stats/index.ts',
		'services/machine-drive-stats/index': 'src/services/machine-drive-stats/index.ts',
		'services/machine-nic-stats/index': 'src/services/machine-nic-stats/index.ts',
		'services/machine-drive-phys/index': 'src/services/machine-drive-phys/index.ts',
		'services/volume/index': 'src/services/volume/index.ts',
		'services/volume-cifs-share/index': 'src/services/volume-cifs-share/index.ts',
		'services/volume-nfs-share/index': 'src/services/volume-nfs-share/index.ts',
		'services/volume-snapshot/index': 'src/services/volume-snapshot/index.ts',
		'services/volume-sync/index': 'src/services/volume-sync/index.ts',
		'services/nas-service/index': 'src/services/nas-service/index.ts',
		'services/nas-service-user/index': 'src/services/nas-service-user/index.ts',
		'services/volume-browser/index': 'src/services/volume-browser/index.ts',
		'services/file/index': 'src/services/file/index.ts',
	},
	format: ['esm', 'cjs'],
	dts: true,
	sourcemap: true,
	clean: true,
	target: 'es2022',
	outDir: 'dist',
	splitting: true,
	treeshake: true,
});
